name: findsecbugs-hybrid-plugin
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1
on:
  push:
    branches:
      - master
  schedule:
    - cron: 15 21 * * 1-5
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  findsecbugs-hybrid-scan:
    steps:
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1
      - name: findsec hybrid plugin scan
        uses: cloudbees-io/findsecbugs-hybrid-plugin@main
        with:
          binary-tar-path: ./vulnerablesqlapp.tar
